stages:
  - test
  - build-docker
  - deploy 

.test_demo:
  stage: test
  image: node:16.13.1-alpine
  script:
    - echo "testing testing"

.test:
  stage: test
  image: node:16.13.1-alpine
  script:
    - cd client
    - yarn install 
    - yarn jest

.build_backend:
  stage: build-docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t gerrome/mern-stack-app_server:1 .
    - docker push gerrome/mern-stack-app_server:1

.build_frontend:
  stage: build-docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t gerrome/mern-stack-app_client:1 ./client
    - docker push gerrome/mern-stack-app_client:1


deploy_containers:
  stage: deploy
  before_script: 
    - apt-get update -qq
    - apt-get install -qq git # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh victor@10.0.3.15 "cd K8s"
  only:
    - master
  

