stages:
  - test
  - build-docker

test_demo:
  stage: test
  image: node:16.13.1-alpine
  script:
    - echo "testing testing"

.test_vuejs:
  stage: test
  image: node:16.13.1-alpine
  script:
    - cd client
    - yarn install 
    - yarn jest

build_django:
  stage: build-docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t gerrome/mern-stack-app_server:1 .
    - docker push gerrome/mern-stack-app_server:1

build_vue-nginx:
  stage: build-docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t gerrome/mern-stack-app_client:1 ./client
    - docker push gerrome/mern-stack-app_client:1

