stages:
  - test
  - build-docker
  - deploy 

.test_demo:
  stage: test
  image: node:16.13.1-alpine
  script:
    - echo "testing testing"

.test:
  stage: test
  image: node:16.13.1-alpine
  script:
    - cd client
    - yarn install 
    - yarn jest

.build_backend:
  stage: build-docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t gerrome/mern-stack-app_server:1 .
    - docker push gerrome/mern-stack-app_server:1

.build_frontend:
  stage: build-docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t gerrome/mern-stack-app_client:1 ./client
    - docker push gerrome/mern-stack-app_client:1


deploy_containers:
  image: ubuntu:latest
  stage: deploy
  script:
    - chmod 400 $SSH_PRIVATE_KEY
    - apk update && apk add openssh-client 
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no victor@192.168.56.111 "cd MERN-Stack-App"
  only:
    - master
  

