version: "3.3"

services:
    client:
      build:
        context: ./client
      stdin_open: true
      ports:
        - 3000:3000

    server:
      build:
        context: .
      ports:
        - 5000:5000
      depends_on:
        - mongo

    mongo:
      image: mongo
      ports: 
        - 27017:27017
      environment:
        - MONGO-INITDB_ROOT_USERNAME=admin
        - MONGO-INITDB_ROOT_PASSWORD=password 


 